/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"
#include <stdio.h>   // para printf()
#include <stdlib.h>  // para exit()


void perform_rpc_call(char *host, int num1, char op, int num2) {
    CLIENT *clnt;
    int *result;
    numbers args;

    args.a = num1;
    args.b = num2;

    clnt = clnt_create(host, CALC_PROG, CALC_VERS, "udp");
    if (clnt == NULL) {
        clnt_pcreateerror(host);
        exit(1);
    }

	printf("\nDEBUG - Enviando: a = %d, b = %d\n", args.a, args.b);
    switch (op) {
        case '+':
            result = add_1(&args, clnt);
            break;
        case '-':
            result = sub_1(&args, clnt);
            break;
        case '*':
            result = mult_1(&args, clnt);
            break;
        case '/':
            result = divide_1(&args, clnt);
            break;
        default:
            fprintf(stderr, "Operador inválido: %c\n", op);
            exit(1);
    }

    if (result == (int *) NULL) {
        clnt_perror(clnt, "call failed");
    } else {
        printf("Resultado: %d %c %d = %d\n", num1, op, num2, *result);
    }

    clnt_destroy(clnt);
}


int main( int argc, char* argv[] )
{
	char *host;

	if(argc != 5) {
		 fprintf(stderr, "Uso: %s <host> <num1> <operador> <num2>\n", argv[0]);
		exit(1);
	}
	host = argv[1];
	int num1 = atoi(argv[2]);
	char operator = argv[3][0];
	int num2 = atoi(argv[4]);
	printf("number 1 %d \n", num1);
	printf("number 2 %d \n", num2);
	perform_rpc_call(host, num1, operator, num2);

	return 0;
}
