/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"
#include <stdlib.h>
#include <stdio.h>

int *
add_1_svc(numbers *argp, struct svc_req *rqstp)
{

	static int  result;

	printf("\nRequisição recebida: add(%d, %d)\n", argp->a, argp->b);

	result = argp->a + argp->b;

	return(&result);
}

int *
sub_1_svc(numbers *argp, struct svc_req *rqstp)
{

	static int  result;

	printf("\nRequisição recebida: sub(%d, %d)\n", argp->a, argp->b);

	result = argp->a - argp->b;

	return(&result);
}

int *
mult_1_svc(numbers *argp, struct svc_req *rqstp)
{

	static int  result;

	printf("\nRequisição recebida: mul(%d, %d)\n", argp->a, argp->b);
	result = argp->a * argp->b;

	return(&result);
}

int *
divide_1_svc(numbers *argp, struct svc_req *rqstp)
{

	static int  result;

	printf("\nDEBUG - Recebido: a = %d, b = %d\n", argp->a, argp->b);
	printf("\nRequisição recebida: divide(%d, %d) -> [resultado em inteiro]\n", argp->a, argp->b);

	if(argp->b == 0){
		printf("Erro: divisao por zero. Retornando -400 (bad request)\n");
		result = -400;
	} else {
		result = argp->a / argp->b;
	}

	return(&result);
}
