/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALC_H_RPCGEN
#define _CALC_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>


struct numbers {
	int a;
	int b;
};
typedef struct numbers numbers;
#ifdef __cplusplus
extern "C" bool_t xdr_numbers(XDR *, numbers*);
#elif __STDC__
extern  bool_t xdr_numbers(XDR *, numbers*);
#else /* Old Style C */
bool_t xdr_numbers();
#endif /* Old Style C */


#define CALC_PROG ((rpc_uint)0x20000001)
#define CALC_VERS ((rpc_uint)1)

#ifdef __cplusplus
#define add ((rpc_uint)1)
extern "C" int * add_1(numbers *, CLIENT *);
extern "C" int * add_1_svc(numbers *, struct svc_req *);
#define sub ((rpc_uint)2)
extern "C" int * sub_1(numbers *, CLIENT *);
extern "C" int * sub_1_svc(numbers *, struct svc_req *);
#define mult ((rpc_uint)3)
extern "C" int * mult_1(numbers *, CLIENT *);
extern "C" int * mult_1_svc(numbers *, struct svc_req *);
#define divide ((rpc_uint)4)
extern "C" int * divide_1(numbers *, CLIENT *);
extern "C" int * divide_1_svc(numbers *, struct svc_req *);

#elif __STDC__
#define add ((rpc_uint)1)
extern  int * add_1(numbers *, CLIENT *);
extern  int * add_1_svc(numbers *, struct svc_req *);
#define sub ((rpc_uint)2)
extern  int * sub_1(numbers *, CLIENT *);
extern  int * sub_1_svc(numbers *, struct svc_req *);
#define mult ((rpc_uint)3)
extern  int * mult_1(numbers *, CLIENT *);
extern  int * mult_1_svc(numbers *, struct svc_req *);
#define divide ((rpc_uint)4)
extern  int * divide_1(numbers *, CLIENT *);
extern  int * divide_1_svc(numbers *, struct svc_req *);

#else /* Old Style C */
#define add ((rpc_uint)1)
extern  int * add_1();
extern  int * add_1_svc();
#define sub ((rpc_uint)2)
extern  int * sub_1();
extern  int * sub_1_svc();
#define mult ((rpc_uint)3)
extern  int * mult_1();
extern  int * mult_1_svc();
#define divide ((rpc_uint)4)
extern  int * divide_1();
extern  int * divide_1_svc();
#endif /* Old Style C */

#endif /* !_CALC_H_RPCGEN */
